[build]
builder = "nixpacks"
command = "npm run build"

[variables]
NODE_VERSION = "18"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/v1/user/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 